services:
  yy-pay:
    image: "${APP_IMAGE:?APP_IMAGE requis}"
    container_name: yy-pay
    pull_policy: always
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      IWM_API_BASE_URL: "https://kernel-core.yowyob.com/kernel-api"
      IWM_CLIENT_ID: "yy-pay"
      IWM_API_KEY: "${IWM_API_KEY:?}"
      IWM_TENANT_ID: "11111111-1111-1111-1111-111111111111"
      PAYMENT_PAYER_REFERENCE: "+237611223344"
      COOKIE_ACCESS_TOKEN: "yy_pay_access_token"
      COOKIE_REFRESH_TOKEN: "yy_pay_refresh_token"
      COOKIE_ORGANIZATION_ID: "yy_pay_organization_id"
      COOKIE_WALLET_ID: "yy_pay_wallet_id"
      COOKIE_ACTOR_ID: "yy_pay_actor_id"
      PAYMENT_CALLBACK_URL: "https://kernel-core.yowyob.com/pay/console?payment=success"
      PAYMENT_FAILURE_CALLBACK_URL: "https://kernel-core.yowyob.com/pay/console?payment=failure"
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://127.0.0.1:3000/pay >/dev/null 2>&1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 15
      start_period: 45s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.yy-pay.rule=Host(`kernel-core.yowyob.com`) && PathPrefix(`/pay`)"
      - "traefik.http.routers.yy-pay.entrypoints=websecure"
      - "traefik.http.routers.yy-pay.priority=200"
      - "traefik.http.routers.yy-pay.tls=true"
      - "traefik.http.routers.yy-pay.tls.certresolver=letsencrypt"
      - "traefik.http.services.yy-pay.loadbalancer.server.port=3000"
      - "traefik.docker.network=yowyob"
    networks: [yowyob]
networks:
  yowyob: { external: true, name: yowyob }
