/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/users/me/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMyPlan"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateOnboarding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/identity-onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateIdentityOnboarding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMyAvatar"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/{userId}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminResetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/select-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["selectContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/phone-verification/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestPhoneVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/phone-verification/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPhoneVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/password-reset/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issuePasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disableMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/spaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOwnedSpace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login/mfa/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmLoginMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["forgotPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-verification/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resendEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-verification/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-verification/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmEmailVerification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/discover-sign-up-contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["discoverSignUpContexts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/discover-contexts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["discoverContexts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/captcha": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["issueCaptcha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/captcha/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyCaptcha"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["myMemberships"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdatePlanRequest: {
            plan: string;
        };
        ApiResponseUserAccountResponse: {
            success?: boolean;
            data?: components["schemas"]["UserAccountResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        UserAccountResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            actorId?: string;
            username?: string;
            email?: string;
            phoneNumber?: string;
            authProvider?: string;
            externalSubject?: string;
            status?: string;
            plan?: string;
            onboardingStatus?: string;
            /** Format: int32 */
            onboardingStep?: number;
            accountType?: string;
            businessType?: string;
            onboardingPayload?: string;
            emailVerified?: boolean;
            /** Format: date-time */
            emailVerifiedAt?: string;
            phoneVerified?: boolean;
            /** Format: date-time */
            phoneVerifiedAt?: string;
            mfaEnabled?: boolean;
            mfaChannel?: string;
            /** Format: uuid */
            avatarId?: string;
            organizations?: components["schemas"]["UserOrganizationAccessResponse"][];
        };
        UserOrganizationAccessResponse: {
            /** Format: uuid */
            organizationId?: string;
            organizationCode?: string;
            shortName?: string;
            longName?: string;
            displayName?: string;
            legalName?: string;
            services?: string[];
        };
        UpdateOnboardingRequest: {
            /** Format: int32 */
            step?: number;
            status?: string;
        };
        UpdateIdentityOnboardingRequest: {
            accountType: string;
            businessType?: string;
            /** Format: int32 */
            step?: number;
            status?: string;
            data?: {
                [key: string]: unknown;
            };
        };
        UpdateAvatarRequest: {
            /** Format: uuid */
            avatarId?: string;
        };
        AdminResetPasswordResponse: {
            /** Format: uuid */
            userId?: string;
            username?: string;
            email?: string;
            temporaryPassword?: string;
        };
        ApiResponseAdminResetPasswordResponse: {
            success?: boolean;
            data?: components["schemas"]["AdminResetPasswordResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        PublicSignUpRequest: {
            /** Format: uuid */
            tenantId?: string;
            signUpSelectionToken?: string;
            contextId?: string;
            firstName: string;
            lastName: string;
            username?: string;
            /** Format: email */
            email: string;
            phoneNumber?: string;
            password?: string;
            socialProvider?: string;
            externalSubject?: string;
            captchaVerificationToken?: string;
            accountType?: string;
            businessType?: string;
            onboardingData?: {
                [key: string]: unknown;
            };
        };
        ApiResponseObject: {
            success?: boolean;
            data?: unknown;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        SelectLoginContextRequest: {
            selectionToken: string;
            contextId: string;
            /** Format: uuid */
            organizationId?: string;
        };
        ApiResponseContextualLoginResponse: {
            success?: boolean;
            data?: components["schemas"]["ContextualLoginResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ContextualLoginResponse: {
            /** Format: uuid */
            selectedTenantId?: string;
            /** Format: uuid */
            selectedOrganizationId?: string;
            session?: components["schemas"]["LoginResponse"];
        };
        LoginResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            actorId?: string;
            username?: string;
            email?: string;
            phoneNumber?: string;
            authProvider?: string;
            externalSubject?: string;
            status?: string;
            plan?: string;
            onboardingStatus?: string;
            /** Format: int32 */
            onboardingStep?: number;
            accountType?: string;
            businessType?: string;
            onboardingPayload?: string;
            emailVerified?: boolean;
            /** Format: date-time */
            emailVerifiedAt?: string;
            phoneVerified?: boolean;
            /** Format: date-time */
            phoneVerifiedAt?: string;
            mfaEnabled?: boolean;
            mfaChannel?: string;
            accessToken?: string;
            sessionToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            /** Format: int64 */
            refreshExpiresInSeconds?: number;
            /** Format: date-time */
            refreshExpiresAt?: string;
            sharedSession?: components["schemas"]["SharedSsoSessionResponse"];
            authorities?: string[];
            organizations?: components["schemas"]["UserOrganizationAccessResponse"][];
        };
        SharedSsoSessionResponse: {
            token?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
        };
        ResetPasswordRequest: {
            resetToken: string;
            newPassword: string;
        };
        RegisterUserRequest: {
            /** Format: uuid */
            actorId?: string;
            username: string;
            /** Format: email */
            email: string;
            phoneNumber?: string;
            password?: string;
            authProvider: string;
            externalSubject?: string;
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        ApiResponseRefreshTokenResponse: {
            success?: boolean;
            data?: components["schemas"]["RefreshTokenResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        RefreshTokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** Format: int64 */
            accessExpiresInSeconds?: number;
            /** Format: int64 */
            refreshExpiresInSeconds?: number;
            /** Format: date-time */
            refreshExpiresAt?: string;
        };
        IssueOtpRequest: {
            channel: string;
            recipient: string;
            purpose?: string;
        };
        ApiResponseOtpChallengeResponse: {
            success?: boolean;
            data?: components["schemas"]["OtpChallengeResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        OtpChallengeResponse: {
            deliveryMode?: string;
            challengeToken?: string;
            codePreview?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
        };
        ConfirmMfaRequest: {
            challengeToken: string;
            code: string;
        };
        IssuePasswordResetRequest: {
            selectionToken: string;
            contextId: string;
        };
        ApiResponseIssuedAuthChallengeResponse: {
            success?: boolean;
            data?: components["schemas"]["IssuedAuthChallengeResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        IssuedAuthChallengeResponse: {
            deliveryMode?: string;
            challengeTokenPreview?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
        };
        VerifyOtpRequest: {
            challengeToken: string;
            code: string;
            purpose?: string;
        };
        ApiResponseOtpVerificationResponse: {
            success?: boolean;
            data?: components["schemas"]["OtpVerificationResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        OtpVerificationResponse: {
            verified?: boolean;
            channel?: string;
            recipient?: string;
            purpose?: string;
        };
        EnableMfaRequest: {
            channel: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: unknown;
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        LoginRequest: {
            principal: string;
            password: string;
        };
        ConfirmMfaLoginRequest: {
            mfaToken: string;
            code: string;
        };
        ApiResponseLoginResponse: {
            success?: boolean;
            data?: components["schemas"]["LoginResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        IdentifyAccountRequest: {
            principal: string;
        };
        ApiResponseIdentifyAccountResponse: {
            success?: boolean;
            data?: components["schemas"]["IdentifyAccountResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        IdentifyAccountResponse: {
            principal?: string;
            accountExists?: boolean;
            nextStep?: string;
            /** Format: int64 */
            matchingAccountCount?: number;
        };
        ForgotPasswordRequest: {
            principal: string;
        };
        ApiResponseForgotPasswordResponse: {
            success?: boolean;
            data?: components["schemas"]["ForgotPasswordResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        ForgotPasswordResponse: {
            principal?: string;
            /** Format: int64 */
            matchingAccountCount?: number;
            selectionToken?: string;
            /** Format: int64 */
            selectionTokenExpiresInSeconds?: number;
            contexts?: components["schemas"]["PasswordResetContextResponse"][];
        };
        PasswordResetContextResponse: {
            contextId?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            actorId?: string;
            username?: string;
            email?: string;
        };
        ConfirmEmailVerificationRequest: {
            verificationToken: string;
        };
        DiscoverSignUpContextsRequest: {
            organizationCode: string;
        };
        ApiResponseDiscoverSignUpContextsResponse: {
            success?: boolean;
            data?: components["schemas"]["DiscoverSignUpContextsResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        DiscoverSignUpContextsResponse: {
            selectionToken?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            contexts?: components["schemas"]["SelectableSignUpContextResponse"][];
        };
        SelectableSignUpContextResponse: {
            contextId?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            organizationId?: string;
            organizationCode?: string;
            organizationName?: string;
            organizationType?: string;
        };
        ApiResponseDiscoverLoginContextsResponse: {
            success?: boolean;
            data?: components["schemas"]["DiscoverLoginContextsResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        DiscoverLoginContextsResponse: {
            selectionToken?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
            contexts?: components["schemas"]["DiscoveredLoginContextResponse"][];
        };
        DiscoveredLoginContextResponse: {
            contextId?: string;
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            userId?: string;
            /** Format: uuid */
            actorId?: string;
            organizations?: components["schemas"]["UserOrganizationAccessResponse"][];
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        ApiResponseCaptchaChallengeResponse: {
            success?: boolean;
            data?: components["schemas"]["CaptchaChallengeResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CaptchaChallengeResponse: {
            captchaToken?: string;
            prompt?: string;
            answerPreview?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
        };
        VerifyCaptchaRequest: {
            captchaToken: string;
            answer: string;
        };
        ApiResponseCaptchaVerificationResponse: {
            success?: boolean;
            data?: components["schemas"]["CaptchaVerificationResponse"];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        CaptchaVerificationResponse: {
            captchaVerificationToken?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
        };
        ApiResponseListUserMembershipResponse: {
            success?: boolean;
            data?: components["schemas"]["UserMembershipResponse"][];
            message?: string;
            errorCode?: string;
            /** Format: date-time */
            timestamp?: string;
        };
        UserMembershipResponse: {
            /** Format: uuid */
            tenantId?: string;
            /** Format: uuid */
            organizationId?: string;
            organizationCode?: string;
            organizationName?: string;
            roleCode?: string;
            roleName?: string;
            scopeType?: string;
            permissions?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    updateMyPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    updateOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOnboardingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    updateIdentityOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIdentityOnboardingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    updateMyAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAvatarRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    adminResetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAdminResetPasswordResponse"];
                };
            };
        };
    };
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicSignUpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseObject"];
                };
            };
        };
    };
    selectContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectLoginContextRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseContextualLoginResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseRefreshTokenResponse"];
                };
            };
        };
    };
    requestPhoneVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOtpChallengeResponse"];
                };
            };
        };
    };
    confirmPhoneVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMfaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    issuePasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssuePasswordResetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIssuedAuthChallengeResponse"];
                };
            };
        };
    };
    issueOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOtpChallengeResponse"];
                };
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOtpVerificationResponse"];
                };
            };
        };
    };
    enableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnableMfaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOtpChallengeResponse"];
                };
            };
        };
    };
    disableMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    confirmMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMfaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    createOwnedSpace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseObject"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: {
                Authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseObject"];
                };
            };
        };
    };
    confirmLoginMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmMfaLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    identify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentifyAccountRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIdentifyAccountResponse"];
                };
            };
        };
    };
    forgotPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseForgotPasswordResponse"];
                };
            };
        };
    };
    resendEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIssuedAuthChallengeResponse"];
                };
            };
        };
    };
    requestEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseIssuedAuthChallengeResponse"];
                };
            };
        };
    };
    confirmEmailVerification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailVerificationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    discoverSignUpContexts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoverSignUpContextsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDiscoverSignUpContextsResponse"];
                };
            };
        };
    };
    discoverContexts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDiscoverLoginContextsResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    issueCaptcha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCaptchaChallengeResponse"];
                };
            };
        };
    };
    verifyCaptcha: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCaptchaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCaptchaVerificationResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserAccountResponse"];
                };
            };
        };
    };
    myMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListUserMembershipResponse"];
                };
            };
        };
    };
}
